version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud config set project $GOOGLE_PROJECT_ID
      - checkout
      - run: echo "Building"
      - run: kubectl get pods

