resources:
  -
    type: container.v1.cluster
    name: kube-cluster-deployment
    properties:
      zone: europe-west1-b
      cluster:
        name: kube-cluster
        initialNodeCount: 3
        nodeConfig:
          machineType: f1-micro
          diskSizeGb: 10
          oauthScopes:
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring

